### ISSUE TITLE
Create toolBar

### ISSUE THREAD

**Issue by corentin-P** [Samtaupe/Id-eFixe#1]
- [x] Création de la barre des tâches sur PC
- [X] Définir les liens de toutes les pages vers lesquelles nous seront redirigé et les noter dans le wiki : https://github.com/Samtaupe/Id-eFixe/wiki
- [x] Ne pas oublier de cocher la case dans le ReadMe
![grafik](https://github.com/Samtaupe/Id-eFixe/assets/70685440/c6e6d782-36e1-4efa-8dda-ea08ee79187d)

**Comment by Samtaupe** [comment]
- [x] Faire le responsive donc la version mobile
